### ISSUE TITLE
The latest release v0.26.3 is throwing the following exception while starting the tomcat server.

### ISSUE THREAD

**Issue by krishna-vasudev** [redhat-developer/rsp-server-community#173] opened 2023-03-05 07:17 UTC
os: windows 10

error:
```
org.apache.catalina.startup.Bootstrap initClassLoaders
SEVERE: Class loader creation threw exception
java.io.IOException: Invalid argument
    at java.io.WinNTFileSystem.canonicalize0(Native Method)
    at java.io.WinNTFileSystem.canonicalize(Unknown Source)
    at java.io.File.getCanonicalPath(Unknown Source)
    at java.io.File.getCanonicalFile(Unknown Source)
    at org.apache.catalina.startup.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:168)
    at org.apache.catalina.startup.Bootstrap.createClassLoader(Bootstrap.java:201)
    at org.apache.catalina.startup.Bootstrap.initClassLoaders(Bootstrap.java:146)
    at org.apache.catalina.startup.Bootstrap.init(Bootstrap.java:256)
    at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:455)
```

on downgrading to previous version it works fine.

Please check this issue at the earliest.

**Comment by robstryker** [comment] 2023-03-06 20:00
I realize this issue was opened first, but since hte other issue has more discussion, i'll leave that one open. 

Duplicate of https://github.com/redhat-developer/rsp-server-community/issues/174

**Closed by robstryker** 2023-03-06 20:00 UTC
