### ISSUE TITLE
Publish to OpenVSX

### ISSUE THREAD

**Issue by filiptronicek** [redhat-developer/rsp-server-community#127] opened 2022-06-07 16:21 UTC
Hello to everyone from the Red Hat team 👋! 

I would like to ask you to publish this extension to the Open VSX marketplace.

## Context

Unfortunately, as Microsoft prohibits usages of the Microsoft marketplace by any other products or redistribution of `.vsix` files from it, in order to use VS Code extensions in non-Microsoft products, we kindly ask that you take ownership of the VS Code extension namespace in [OpenVSX](https://open-vsx.org/) and publish this extension on Open VSX.

## What is OpenVSX? Why does it exist?

OpenVSX is a vendor neutral alternative to the MS marketplace used by most other derivatives of VS Code like [VSCodium](https://vscodium.com/), [Gitpod](gitpod.io), [OpenVSCode](https://github.com/gitpod-io/openvscode-server), [Theia](https://theia-ide.org/) based IDEs, and so on.

This extension is one of the extensions VS Code recommends users instead of `SummerSun.vscode-jetty` and `adashen.vscode-tomcat`.

The namespace for the extension is already claimed and owned by Red Hat [[1](https://github.com/EclipseFdn/open-vsx.org/issues/6)], so it should be really easy to publish. If it is wanted, I'd be happy to contribute an update to the [release workflow](https://github.com/redhat-developer/rsp-server-community/blob/master/.github/workflows/release.yml) to enable publishing to OpenVSX.

**Comment by mohitsuman** [comment] 2023-05-03 21:26
Hi @filiptronicek I see you had requested this issue a long time back. we now published the server connector community version to open-vsx https://open-vsx.org/extension/redhat/vscode-community-server-connector. Please feel free to try it out and let us know any feedbacks.

**Comment by robstryker** [comment] 2023-05-04 03:09
https://github.com/redhat-developer/rsp-server-community/pull/191

Closing this issue for now. Please feel free to re-open if it is not published. Please open a new issue if the open-vsx releases do not work as intended.

**Closed by robstryker** 2023-05-04 03:09 UTC

**Comment by filiptronicek** [comment] 2023-05-04 05:15
thanks so much to you both, it's awesome seeing the extension published!
