### ISSUE TITLE
Tomcat heap space grows out of control with redeloyments

### ISSUE THREAD

**Issue by aydewa** [redhat-developer/rsp-server-community#189] opened 2022-11-29 11:54 UTC
It seems that the server-connector eat much RAM after long running. How can I set its JVM properties such as -`Xms` and `-Xmx`?

From the following picture, I have to manually perform GC at **06:42 PM**. But the heap space is already reached > 1G. How can I limit the maximum heap space?
![Screenshot from 2022-11-29 18-42-57](https://user-images.githubusercontent.com/105286666/204522828-713a2a89-764b-4a5a-8407-fe2cc57f9a57.png)

![Screenshot from 2022-11-29 18-43-27](https://user-images.githubusercontent.com/105286666/204522857-4e601258-2350-41db-9d3a-c678cde1da78.png)

**Comment by robstryker** [comment] 2023-05-01 18:45
@aydewa  you can customize a tomcat instance's vm arguments by right-clicking on the server in the server view, selecting 'edit server', and changing the override value to true, and then adding your custom vm flags to the appropriate setting in that file. 

Let me know if you need more assistance here.

**Comment by aydewa** [comment] 2023-05-03 13:48
Yes, it works. The configuration is in the server connector itself. But I think Tomcat itself doesn't release the heap every deployment. Whether or not I set the `Xmx`, the heap is always grow up until it reached OOM. Anyway, thanks for your help.

**Comment by robstryker** [comment] 2023-05-04 18:21
If you ever figure out how to prevent that, feel free to return here and let me know! I'd be happy to fix it on my end if I know what to do that can release the heap or ensure a cleanup / garbage collection somehow.

**Comment by robstryker** [comment] 2023-05-10 16:07
Gonna close this issue since it's not a bug with this repo.

**Closed by robstryker** 2023-05-10 16:07 UTC
