### ISSUE TITLE
Unable to debug Tomcat app - Getting error java.lang.IllegalStateException: Cannot evaluate, please specify projectName in launch.json..

### ISSUE THREAD

**Issue by rwankar** [redhat-developer/rsp-server-community#85] opened 2021-03-09 03:29 UTC
I'm not sure if this is the right place to report this but I'm using the rsp connector and this started just after updating to the latest 0.23.7 version. It worked before.

Steps to reproduce.

1. Unzip the attached sample-tomcat.zip (You will get the sample-tomcat web app and the rsp server config file 'sample')
2. Edit the rsp server config file "sample" and put in the path to tomcat-sample directory
3. Place the rsp server config file "sample" in your rsp/redhat-community-server-connector/servers directory. For me it was in ~/.rsp/redhat-community-server-connector/servers
4. Start VSCode and open the HelloWorld.java file sample-tomcat/webapps/sample/WEB-INF/classes/HelloWorld.java
5. Set a breakpoint at line 24 (we want to watch the variable 'message').
6. Launch the server sample in Debug mode.
7. Point your browser to localhost:8888/sample/hello
8. The breakpoint should be activated
9. Mouseover the variable 'message' (you'll notice that it doesn't show contents of the variable like it usually does)
10. Add watch for variable 'message'. You'll get the error "IllegalStateException..."

[sample-tomcat.zip](https://github.com/redhat-developer/rsp-server-community/files/6105677/sample-tomcat.zip)

`[Error - 2:14:32 PM] 08-Mar-2021, 2:14:32 PM No project is available for evaluation.
[Error - 2:14:32 PM] 08-Mar-2021, 2:14:32 PM [error response][evaluate]: Cannot evaluate because of java.lang.IllegalStateException: Cannot evaluate, please specify projectName in launch.json..
Cannot evaluate because of java.lang.IllegalStateException: Cannot evaluate, please specify projectName in launch.json..
com.microsoft.java.debug.core.DebugException: Cannot evaluate because of java.lang.IllegalStateException: Cannot evaluate, please specify projectName in launch.json..
    at com.microsoft.java.debug.core.adapter.AdapterUtils.createCompletionException(AdapterUtils.java:246)
    at com.microsoft.java.debug.core.adapter.handler.EvaluateRequestHandler.lambda$handle$0(EvaluateRequestHandler.java:147)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.IllegalStateException: Cannot evaluate, please specify projectName in launch.json.
    at com.microsoft.java.debug.plugin.internal.eval.JdtEvaluationProvider.findJavaProjectByType(JdtEvaluationProvider.java:277)
    at com.microsoft.java.debug.plugin.internal.eval.JdtEvaluationProvider.ensureDebugTarget(JdtEvaluationProvider.java:405)
    at com.microsoft.java.debug.plugin.internal.eval.JdtEvaluationProvider.evaluate(JdtEvaluationProvider.java:140)
    at com.microsoft.java.debug.plugin.internal.eval.JdtEvaluationProvider.evaluate(JdtEvaluationProvider.java:115)
    at com.microsoft.java.debug.core.adapter.handler.EvaluateRequestHandler.lambda$handle$0(EvaluateRequestHandler.java:84)
    ... 7 more
`

**Comment by rwankar** [comment] 2021-03-09 03:32
HelloWorld.java was compiled using Java 11. To use another version, go to the sample-tomcat/webapps/sample/WEB-INF/classes directory and run the command

`javac -cp ../lib/servlet-api.jar HelloWorld.java`

**Comment by rwankar** [comment] 2021-03-09 03:44
I stand corrected. I misread the date of the latest release. It was Feb 15 [https://marketplace.visualstudio.com/items?itemName=redhat.vscode-community-server-connector&ssr=false#version-history](url) It worked after that. So something else probably caused this.

**Comment by robstryker** [comment] 2021-03-09 21:37
Thanks for the detailed bug report. I'll look into this ASAP.   For now I'll link you to https://github.com/microsoft/vscode-java-debug/issues/843#issuecomment-718995372  for some reference. Apparently someone there had a similar issue, and the fix was to change your project name in the launch.json to match something else. I can look into it further.

**Comment by rwankar** [comment] 2021-03-10 01:18
@robstryker , I did see that. However there is no launch.json file in this case.

**Comment by robstryker** [comment] 2021-03-10 20:29
Hi @rwankar :+1: 

I ran through your steps and, I'm sorry to say, it... seems to work for me.  :: duck my head so you dont whack me ::

Can you tell me what versions of different extensions you have in your environment?

Linux rawbeast 5.8.18-100.fc31.x86_64 
vscode 1.53.2
java version "11.0.2" 2019-01-15 LTS
Community server connector 0.23.10
remote server protocol ui: 0.23.8
debugger for java:  0.31.0
java extension pack: 0.13.0
Java test runner: 0.28.1


Seriously though, it seems to work. Maybe we have different environments.

**Comment by rwankar** [comment] 2021-03-11 16:08
@robstryker, really appreicate you checking. Here is my environment.

Mac OS Bigsur 11.2
vscode 1.54.1
java version: OpenJDK Runtime Environment Corretto-11.0.8.10.1 (build 11.0.8+10-LTS)
Community server connector 0.23.10
remote server protocol ui: 0.23.7 (I don't see the 0.23.8 version you are using)
debugger for java: 0.31.0
java extension pack: 0.13.0
Java test runner: disabled.

So I spent almost the day trying to debug this and it appears to be a MacOS issue. Works fine on Linux.

1. In the zip I sent over, the .vscode directory is missing. So it works fine (even on Mac)
2. If you have the .vscode directory with settings.json file then the issue is noticed. I've pasted my settings.json file below.

It appears that there is some caching being done by the language servers. What I mean is...

1. Start with no .vscode/settings.json and test that it works
2. Stop VSCode, add the .vscode/settings.json file and restart VSCode. It will work.
3. Now, stop VSCode.
4. Remove the caches (User/workspaceStorage CachedData/ Cache/ Code\ Cache/) from VSCode directory
5. Restart VSCode and check. Now you will see the issue.

I've noticed that sometimes the language server process hangs around after exiting VSCode. Not sure if that has an impact too.

Here is my settings.json file...

`{
    "java.dependency.packagePresentation": "hierarchical",
    "java.dependency.syncWithFolderExplorer": true,
    "java.import.maven.enabled": false,
    "java.project.referencedLibraries": {
        "include": [
            "lib/**/*.jar",
            "webapps/sample/WEB-INF/lib/**/*.jar"
        ],
        "exclude": [
        ]
    },
    "java.autobuild.enabled": false
}`

**Comment by rwankar** [comment] 2021-03-12 04:13
Glad to report that I located the issue. It is the setting `"java.autobuild.enabled": false`. Can be reproduced on MacOS and Linux. Also, caching was making it hard to locate. So to replicate,

1. Add the setting to settings.json file
2. Close VSCode completely.
3. Remove the caches (User/workspaceStorage CachedData/ Cache/ Code\ Cache/) from your VSCode directory
4. Restart VSCode and check. Now you will see the issue.

To make it work, remove the setting, quit VSCode, remove the caches again and restart VSCode. It will work. So there is no launch.json file and no "projectName" is set.

Seems like a bug in atleast that the error message is misleading. I'm not sure which package is responsible for it.

**Comment by robstryker** [comment] 2021-03-12 19:27
So I've done all that and I can't even replicate. I tried to get on with a colleague of mine and he was having trouble even importing your project cleanly and not getting compliation errors. (I did not have this problem). 

To be clear, I put the settings.json file inside sample-tomcat/.vscode/settings.json  and wiped all the caches and reset. But I still can't replicate. Sad.

**Comment by rwankar** [comment] 2021-03-13 05:05
Lucky it works for you. I'm not even sure this has to do with this extension but it would have been good if you could at least reproduce. Here is one final attempt.

I'm attaching 2 new zips. sample-working works, sample-error gives the error. The .vscode/settings.json file is already included. I tried these on Linux Mint 20. I've attached screenshots of the Extensions and also of the watched variables for working and for error cases. I noticed that you were using VSCode 1.53 (mine is 1.54 latest) and Rsp-Ui-Connector v 0.23.8 (mine is 0.23.7).

Steps
1. Stop VSCode if running.
2. Unzip both the zips somewhere
3. place the sample-err and sample-work in ~/.rsp/redhat-community-server-connector/servers directory
4. Edit sample-err and sample-work files and set path to sample-error and sample-working directories
5. Start VSCode
6. Open the folder sample-working
7. Open HelloWorld.java and set breakpoint to line 24
8. Run sample-work server
9. Point browser to localhost:8888/sample/hello
10. Breakpoint should be activated
11. Mouse over variable "message" and you'll see that it shows Hello World text inside it.
12. Stop sample-work server.
13. Open the folder sample-error
14. Open HelloWorld.java again and set breakpoint to line 24
15. Launch sample-err server
16. Point browser to localhost:8888/sample/hello again
17. When breakpoint is activated mouse over the "message" variable and you should notice nothing is shown
18. Open the debug window and add a watch on "message" variable and you should see the exception.

`java -version

openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)`

![Extensions](https://user-images.githubusercontent.com/5335605/111019800-76dfe200-83e7-11eb-92a5-171dacae7760.png)

![Sample-Error](https://user-images.githubusercontent.com/5335605/111019802-79423c00-83e7-11eb-8118-27b6e9fd98c5.png)

![Sample-Working](https://user-images.githubusercontent.com/5335605/111019804-7b0bff80-83e7-11eb-8817-92d759f3c8d9.png)

[sample-error.zip](https://github.com/redhat-developer/rsp-server-community/files/6134196/sample-error.zip)

[sample-working.zip](https://github.com/redhat-developer/rsp-server-community/files/6134199/sample-working.zip)

**Comment by odockal** [comment] 2021-03-15 15:30
Sooo. I managed to configure both working and error server in server provider. I tried both option how to reproduce. So the expected output was to have one working (showing message variable content while I hover over mouse, right?) setup and other that will show nothing and outputs exception in developers console (which is where I spotted the error). 

So.. None is working for me. Both examples were erroneous. I reproduced both times. Ergh... I might have an issue with cache clean up.

**Comment by rwankar** [comment] 2021-03-21 04:14
By "both examples were erroneous" do you mean the examples don't run at all or that you are not seeing the variable content on mouse over? If the latter then are you getting the IllegalStateException under watcher? If you are getting the IllegalStateException then you've replicated the problem.

Not sure why the working example did not work for you. Are you using the exact same versions of VSCode and extensions? If possible do try a fresh VSCode install with those extensions get rid of your .vscode (on Linux, different for others).

**Comment by rwankar** [comment] 2021-03-21 04:16
I'm not sure what more information I can provide. Like I said, this may not even by an issue with this extension. If you don't think it's related then go ahead and close the issue.

**Comment by robstryker** [comment] 2021-03-22 18:37
There's enough weird issues with vscode cropping up that I prefer to keep bugs like this open in case we get others opening similar issues. I'll keep my eyes open for now and see what I can find.

**Comment by lpignotti** [comment] 2022-03-10 18:37
Any updates about this topic? I have the same issue and currently I didn't find any solution about that
vscode 1.65.1
language support for java 1.4.0
red hat commons 0.0.6
remote server protocol 0.23.11
server connector 0.25.2
openjdk version "11.0.14" 2022-01-18

**Comment by codebling** [comment] 2022-03-14 01:13
@lpignotti here's an easy way to get the project name:

Right-click on a Java file (one without a `main()` function) and choose "Run Java" and you'll get a prompt with a few options. This prompt will show the project name. 

[![pop-up menu when Java file is not executable][1]][1]

As you can see in this screenshot of this Ant project, sometimes the project name is unpredictable.

See also [this answer on StackOverflow](https://stackoverflow.com/a/71462120/675721)

  [1]: https://i.stack.imgur.com/wHAA4.png

**Comment by robstryker** [comment] 2022-05-04 17:55
Ok guys...  I'm closing this issue as wont-fix, as it's not really a bug in this codebase here and there's really nothing we COULD reasonably do in this codebase to fix it.   Issue is still here for historical and informational purposes though, but closing it.

**Closed by robstryker** 2022-05-04 17:55 UTC

**Comment by Foxhunter981** [comment] 2022-05-09 16:37
> @lpignotti here's an easy way to get the project name:
> 
> Right-click on a Java file (one without a `main()` function) and choose "Run Java" and you'll get a prompt with a few options. This prompt will show the project name.
> 
> [![pop-up menu when Java file is not executable](https://camo.githubusercontent.com/0234c11c94d15cdc079c7f5422e95849394e72eea1f4b20a09faecab904b6555/68747470733a2f2f692e737461636b2e696d6775722e636f6d2f77484141342e706e67)](https://i.stack.imgur.com/wHAA4.png)
> 
> As you can see in this screenshot of this Ant project, sometimes the project name is unpredictable.
> 
> See also [this answer on StackOverflow](https://stackoverflow.com/a/71462120/675721)

I'm sorry but I'm pretty sure this isn't relevant. We are using the Tomcat extension for Vs-Code and it doesn't consume or use the launch.json. It has some other mysterious implementation that we can't see. I suspect the issue is related to nested projects but your answer isn't going to be getting us any closer sadly.

**Comment by THLIVSQAZ** [comment] 2025-01-15 03:42
Have you solved the problem? I got same error with this

**Comment by robstryker** [comment] 2025-01-20 18:12
No, unfortunately. I've made no progress on this issue.

**Comment by rwankar** [comment] 2025-01-21 03:57
I think I've got this working very reliably for me. Note that my project uses Tomcat web server and I don't have a Maven project.

1. Have a .project file in your project root directory. It looks like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<projectDescription>
    <name>main</name>
    <comment></comment>
    <projects>
    </projects>
    <buildSpec>
    </buildSpec>
    <natures>
        <nature>org.eclipse.jdt.core.javanature</nature>
    </natures>
    <filteredResources>
        <filter>
            <id>1664528976342</id>
            <name></name>
            <type>30</type>
            <matcher>
                <id>org.eclipse.core.resources.regexFilterMatcher</id>
                <arguments>node_modules|\.git|__CREATED_BY_JAVA_LANGUAGE_SERVER__</arguments>
            </matcher>
        </filter>
    </filteredResources>
</projectDescription>
```

2. I also have a .classpath file in the project root folder. My file looks like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
    <classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.launching.macosx.MacOSXType/JavaSE-21"/>
    <classpathentry kind="src" path="services/src/java"/>
    <classpathentry kind="src" path="framework/src/java"/>
    ... (add paths for your source folders)
    <classpathentry kind="output" path="bin"/>
    <classpathentry kind="lib" path="extern/lib/commons-io-2.11.0.jar"/>
    <classpathentry kind="lib" path="extern/lib/commons-cli-1.2.jar"/>
   ... (add path to libraries used in your app.
</classpath>
```

3. Configure the RSP connector launch configuration. I'm on a Mac so my files are under ~/.rsp/redhat-community-server-connector. Here is my configuration. The important thing to note is that the "id" below MUST match the name provided in the .project file above.

```
{
  "args.override.boolean": "true",
  "args.program.override.string": "start",
  "args.shutdown.program.override.string": "stop",
  "args.shutdown.vm.override.string": "", (if you want a custom shutdown)
  "id": "main",
  "id-set": "true",
  "org.jboss.tools.rsp.server.typeId": "org.jboss.ide.eclipse.as.server.tomcat.85",
  "server.base.dir": "/Users/ravi/src/v1.0",
  "server.classpath.additions": "",
  "server.deploy.dir": "${server.base.dir}/webapps/",
  "server.home.dir": "/Users/ravi/src/v1.0",
  "server.http.port": "8888",
  "server.timeout.startup": "1000000",
  "vm.install.path": "/Library/Java/JavaVirtualMachines/amazon-corretto-21.jdk/Contents/Home",
}
```

4. Some times I think VSCode caches get messed up. In that case, I shutdown VSCode and remove the workspace directory from  ~/Library/Application\ Support/Code/User/workspaceStorage/. This contains a directory for each VSCode project. Find the one for your Java project and delete it. Then restart VSCode.

**Comment by cicciozell** [comment] 2025-07-31 21:09
In case anybody comes to this thread for the same problem: I tried rwankar suggestion but it wasn't applicable (the "id" property is not modifiable), and solved by just compiling my source codes with the "-g" switch to include debug info.
